# Generated by Django 5.1.1 on 2024-10-29 03:48

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('last_Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Instrument_Type', models.CharField(choices=[('Guitar', 'Guitar'), ('Piano', 'Piano'), ('Drums', 'Drums'), ('Violin', 'Violin')], max_length=50)),
            ],
        ),
    ]
